# Generated by Django 2.2.5 on 2021-03-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='payment_history',
            fields=[
                ('card_no', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('mobile_no', models.IntegerField()),
                ('payment_method', models.CharField(max_length=20)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
