# Generated by Django 2.2.5 on 2021-03-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentModule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentHistory',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('mobile_no', models.IntegerField()),
                ('payment_method', models.CharField(max_length=20)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='payment_history',
        ),
    ]
