# Generated by Django 2.2.5 on 2021-03-06 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paymentModule', '0002_auto_20210306_1340'),
    ]

    operations = [
        migrations.DeleteModel(
            name='paymentHistory',
        ),
    ]
