# Generated by Django 2.2.5 on 2021-03-06 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paymentModule', '0004_paymenthistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='paymentHistory',
        ),
    ]
