# Generated by Django 2.2.5 on 2021-03-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paymentModule', '0005_delete_paymenthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('mobile_no', models.CharField(max_length=10)),
                ('payment_method', models.CharField(max_length=20)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
