# Generated by Django 2.2.5 on 2021-03-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentModule', '0007_ticket_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_details',
            name='arrival_time',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='ticket_details',
            name='departure_date',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='ticket_details',
            name='departure_time',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='ticket_details',
            name='price',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket_details',
            name='travellers',
            field=models.CharField(max_length=4),
        ),
    ]
