# Generated by Django 2.2.5 on 2021-03-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentModule', '0008_auto_20210307_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_details',
            name='flight_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
