# Generated by Django 3.1.7 on 2021-03-20 06:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paymentModule', '0009_ticket_details_flight_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_details',
            name='arriavl_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
