# Generated by Django 3.1.7 on 2021-03-20 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paymentModule', '0010_ticket_details_arriavl_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket_details',
            old_name='arriavl_date',
            new_name='arrival_date',
        ),
    ]
