# Generated by Django 3.1.7 on 2021-03-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentModule', '0012_auto_20210320_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_details',
            name='cls',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
