# Generated by Django 3.1.7 on 2021-03-31 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paymentModule', '0014_paymenthistory_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ticket_details',
        ),
    ]
