# Generated by Django 2.2.5 on 2021-03-08 09:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('searchFlight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight_details',
            name='arrival_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
